### ISSUE TITLE
what is the meaning of this error...how i can resolve it!!!!!!

### ISSUE THREAD

**Issue by hossemtamsouh** [cyberknight777/PhoneSploit#1]
[
![ScreenShot_20201030162335](https://user-images.githubusercontent.com/73261376/97723822-7a27a080-1acc-11eb-9827-eeb0c2900bf2.png)
](url)

**Comment by cyberknight777** [comment]
What are you running on?

**Comment by hossemtamsouh** [comment]
when i run the shell script of phonesploit

**Comment by polygonnedpotato** [comment]
python running on the native command shell can't really import modules that aren't located in the file system.

**Comment by cyberknight777** [comment]
Btw if you running on termux use termux.sh
